apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx
    demo: service

spec:
  #list of contaiers
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector: #paina vuna pod create ipothadi service dheniki velli attach avvali that is the service.
    name: nginx
    demo: service
  ports:
    - protocol: TCP
      port: 90 #service port we can give anything
      targetPort: 80 #containerPort  , nginx