apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    name: nginx-lb
    demo: service

spec:
  #list of contaiers
  containers:
  - name: nginx-lb
    image: nginx
    ports:
    - containerPort: 80

#---service

apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: #paina vuna pod create ipothadi service dheniki velli attach avvali that is the service.
    name: nginx-lb
    demo: service
  ports:
    - protocol: TCP
      port: 80 #service port we can give anything
      targetPort: 80 #containerPort  , nginx