apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: nginx  
        access:
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          var.paths: ["/var/log/nginx/error.log*"]
    output:
      elasticsearch:
        hosts: ["elasticsearch:9200"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    demo: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      demo: deployment
  template: #template dhagara nuchi kindha antha pod definition , paina antha deployment
    metadata:
      labels:
        app: nginx
        demo: deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts: #e container ki mount cheyali
        - name: nginx-logs #kinda em name echamo adhe name evvali
          mountPath: /var/log/nginx
      - name: filebeat-sidecar  #another container
        image: docker.elastic.co/beats/filebeat:7.17.3
        volumeMounts: #paina vuna image ki malli manam image ni mount cheyali
        - name: nginx-logs 
          mountPath: /var/log/nginx
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml #filebeat thana configure kosam pefer chestundhi..so manam ah configuration kindha estunam.
          subPath: filebeat.yml


      volumes:
      - name: nginx-logs   #volumes manam create cheyali... nginx anee volume create chestana
        emptyDir: {} #emptyDir means we are informing kuberntes pod we storing some data ..so emotyDir dhani automatic ga mount cheyali akkada mount cheyali
      - name: filebeat-config
        configMap:
            name: filebeat-config
            items:
              - key: filebeat.yaml
                path: filebeat.yaml
