apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector: #replicaset labels
    matchLabels:
      app: nginx
      tier: frontend   #template paina nuchi replicaset paidhakka , template dhagara nuchi pod template
  template: #Pod definition
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
