# apiVersion: v1
# kind: Pod
# metadata:
#   name: hello-pod
#   namespace: roboshop
# spec:
#   #list of containers
#   containers:
#   - name: hello-pod
#     image: nginx
#     ports:
#     - containerPort: 80



apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  Namespace: roboshop
spec:
  #list of contaiers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80