apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  labels:
    course: DevOps
    trainer: Charankumar
  annotations:
    com.roboshop.training.duration: "120 HRS"
    jenkins.url: "http://jenkins.com/roboshop/catalogue#45"
spec:
  #list of contaiers
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80