apiVersion: v1
kind: Pod-config
metadata:
  name: charan1
spec:
 containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
      - name: trainer
        valueFrom:
            configMapKeyRef:
            name: charan
            key: trainer

     
