apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  namespace: roboshop
spec:
  #list of contaiers
  containers:
  - name: config-pod
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: course #you can use anything 
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: course

    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: trainer
