# apiVersion: v1
# kind: Pod-config
# metadata:
#   name: charan1
# spec:
#  containers:
#   - name: nginx
#     image: nginx
#     ports:
#     - containerPort: 80
#     env:
#     - name: trainer
#       valueFrom:
#         configMapKeyRef:
#         name: charan
#         key: trainer

apiVersion: v1
kind: Pod
metadata:
  name: charan1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: charan


# apiVersion: v1
# kind: Pod
# metadata:
#   name: config-pod1
# spec:
#   #list of contaiers
#   containers:
#   - name: config-pod1
#     image: nginx
#     ports:
#     - containerPort: 80
#     envFrom:
#     - configMapRef:
#         name: devops-config



     
