apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  cocntainers:
  - name: pod-secret
    image: nginx
    ports:
    - containetPort: 80
    envFrom:
    - configMapRef:
        name: devops-secret