apiVersion: v1
kind: Pod
metadata:
  name: Pod-secrets
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
     - containerport: 80
    envFrom: 
    - secretRef: 
        name: devops-secrets
    

