# apiVersion: v1
# kind: Pod
# metadata:
#   name: pod-secret
# spec:
#   containers:
#   - name: pod-secret
#     image: nginx
#     ports:
#     - containerPort: 80
#     envFrom:
#     - secretRef:
#         name: devops-secret



apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: devops-secret
          key: username

    - name: password
      valueFrom:
        secretKeyRef:
          name: devops-secret
          key: password

